import { createFileRoute, Link } from "@tanstack/react-router";

export const Route = createFileRoute("/privacy")({
  ssr: false,
  head: () => ({ meta: [{ title: "Privacy Policy · Veritech CRO Tool" }] }),
  component: PrivacyPage,
});

function PrivacyPage() {
  return (
    <article className="mx-auto max-w-3xl px-6 py-16 text-[color:var(--light)]">
      <Link to="/" className="text-xs uppercase tracking-widest vt-link">← Home</Link>
      <h1 className="mt-4 text-3xl font-semibold">Privacy Policy</h1>
      <p className="mt-1 text-xs text-[color:var(--muted)]">
        Veritech Digital (veritechdigital.co.za) · POPIA-compliant
      </p>

      <Section title="1. Information we collect">
        <p>We collect the account information you provide (name, email, agency or client details),
        operational data generated by your use of the CRO Tool (audits, scores, page URLs you
        submit), and minimal technical metadata required to run the service securely.</p>
      </Section>

      <Section title="2. How your data is stored">
        <p>All data is stored in our managed cloud backend (PostgreSQL + object storage), hosted in
        secure data centres with industry-standard access controls. Audit reports and assets are
        scoped per agency and per client; row-level security enforces strict tenant isolation.</p>
      </Section>

      <Section title="3. OAuth, tokens, and third-party data">
        <p>If you connect Google Analytics, Search Console, or Semrush, we store the resulting
        access and refresh tokens encrypted with AES-256. These tokens are never returned to the
        browser and are only used by trusted server-side processes to fetch read-only analytics
        data on your behalf.</p>
      </Section>

      <Section title="4. Cookies & session">
        <p>We use a single first-party session token to keep you signed in. We do not run
        third-party analytics or advertising cookies inside the product.</p>
      </Section>

      <Section title="5. Data retention">
        <p>Your data is retained for the lifetime of your account. If your account is closed,
        all personally identifiable data is deleted within 30 days, except where retention is
        required by law.</p>
      </Section>

      <Section title="6. Your POPIA rights">
        <p>You can request access to, correction of, or deletion of your personal information at
        any time. Email{" "}
        <a className="vt-link" href="mailto:privacy@veritechdigital.co.za">
          privacy@veritechdigital.co.za
        </a>.</p>
      </Section>

      <Section title="7. Contact">
        <p>Privacy queries: <a className="vt-link" href="mailto:privacy@veritechdigital.co.za">privacy@veritechdigital.co.za</a><br/>
        Support queries: <a className="vt-link" href="mailto:support@veritechdigital.co.za">support@veritechdigital.co.za</a></p>
      </Section>
    </article>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mt-8">
      <h2 className="text-lg font-semibold text-[color:var(--light)]">{title}</h2>
      <div className="mt-2 space-y-3 text-sm text-[color:var(--light)]/80 leading-relaxed">{children}</div>
    </section>
  );
}
