/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as CompleteSetupRouteImport } from './routes/complete-setup'
import { Route as AccountClosedRouteImport } from './routes/account-closed'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiMemoryRouteImport } from './routes/api/memory'
import { Route as AppPortalRouteImport } from './routes/_app.portal'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as AppPortalIndexRouteImport } from './routes/_app.portal.index'
import { Route as AppDashboardIndexRouteImport } from './routes/_app.dashboard.index'
import { Route as AppAdminIndexRouteImport } from './routes/_app.admin.index'
import { Route as AppPortalIntegrationsRouteImport } from './routes/_app.portal.integrations'
import { Route as AppPortalHistoryRouteImport } from './routes/_app.portal.history'
import { Route as AppPortalConnectRouteImport } from './routes/_app.portal.connect'
import { Route as AppPortalAuditRouteImport } from './routes/_app.portal.audit'
import { Route as AppPortalArchivedRouteImport } from './routes/_app.portal.archived'
import { Route as AppPortalAccountRouteImport } from './routes/_app.portal.account'
import { Route as AppDashboardSuspendedRouteImport } from './routes/_app.dashboard.suspended'
import { Route as AppDashboardSettingsRouteImport } from './routes/_app.dashboard.settings'
import { Route as AppDashboardMarketShareRouteImport } from './routes/_app.dashboard.market-share'
import { Route as AppDashboardIntegrationsRouteImport } from './routes/_app.dashboard.integrations'
import { Route as AppDashboardClientsRouteImport } from './routes/_app.dashboard.clients'
import { Route as AppDashboardAuditRouteImport } from './routes/_app.dashboard.audit'
import { Route as AppAdminUsageRouteImport } from './routes/_app.admin.usage'
import { Route as AppAdminSettingsRouteImport } from './routes/_app.admin.settings'
import { Route as AppAdminLogsRouteImport } from './routes/_app.admin.logs'
import { Route as AppAdminClientsRouteImport } from './routes/_app.admin.clients'
import { Route as AppAdminAgenciesRouteImport } from './routes/_app.admin.agencies'
import { Route as ApiAuthSemrushStartRouteImport } from './routes/api/auth.semrush.start'
import { Route as ApiAuthSemrushCallbackRouteImport } from './routes/api/auth.semrush.callback'
import { Route as ApiAuthGoogleStartRouteImport } from './routes/api/auth.google.start'
import { Route as ApiAuthGoogleCallbackRouteImport } from './routes/api/auth.google.callback'
import { Route as AppPortalAuditsIdRouteImport } from './routes/_app.portal.audits.$id'
import { Route as AppDashboardClientsIdRouteImport } from './routes/_app.dashboard.clients.$id'
import { Route as AppDashboardAuditsIdRouteImport } from './routes/_app.dashboard.audits.$id'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CompleteSetupRoute = CompleteSetupRouteImport.update({
  id: '/complete-setup',
  path: '/complete-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountClosedRoute = AccountClosedRouteImport.update({
  id: '/account-closed',
  path: '/account-closed',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMemoryRoute = ApiMemoryRouteImport.update({
  id: '/api/memory',
  path: '/api/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPortalRoute = AppPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppPortalIndexRoute = AppPortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPortalRoute,
} as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDashboardRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppPortalIntegrationsRoute = AppPortalIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AppPortalRoute,
} as any)
const AppPortalHistoryRoute = AppPortalHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppPortalRoute,
} as any)
const AppPortalConnectRoute = AppPortalConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => AppPortalRoute,
} as any)
const AppPortalAuditRoute = AppPortalAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppPortalRoute,
} as any)
const AppPortalArchivedRoute = AppPortalArchivedRouteImport.update({
  id: '/archived',
  path: '/archived',
  getParentRoute: () => AppPortalRoute,
} as any)
const AppPortalAccountRoute = AppPortalAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppPortalRoute,
} as any)
const AppDashboardSuspendedRoute = AppDashboardSuspendedRouteImport.update({
  id: '/suspended',
  path: '/suspended',
  getParentRoute: () => AppDashboardRoute,
} as any)
const AppDashboardSettingsRoute = AppDashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppDashboardRoute,
} as any)
const AppDashboardMarketShareRoute = AppDashboardMarketShareRouteImport.update({
  id: '/market-share',
  path: '/market-share',
  getParentRoute: () => AppDashboardRoute,
} as any)
const AppDashboardIntegrationsRoute =
  AppDashboardIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AppDashboardRoute,
  } as any)
const AppDashboardClientsRoute = AppDashboardClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AppDashboardRoute,
} as any)
const AppDashboardAuditRoute = AppDashboardAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppDashboardRoute,
} as any)
const AppAdminUsageRoute = AppAdminUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminSettingsRoute = AppAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminLogsRoute = AppAdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminClientsRoute = AppAdminClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminAgenciesRoute = AppAdminAgenciesRouteImport.update({
  id: '/agencies',
  path: '/agencies',
  getParentRoute: () => AppAdminRoute,
} as any)
const ApiAuthSemrushStartRoute = ApiAuthSemrushStartRouteImport.update({
  id: '/api/auth/semrush/start',
  path: '/api/auth/semrush/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSemrushCallbackRoute = ApiAuthSemrushCallbackRouteImport.update({
  id: '/api/auth/semrush/callback',
  path: '/api/auth/semrush/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGoogleStartRoute = ApiAuthGoogleStartRouteImport.update({
  id: '/api/auth/google/start',
  path: '/api/auth/google/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGoogleCallbackRoute = ApiAuthGoogleCallbackRouteImport.update({
  id: '/api/auth/google/callback',
  path: '/api/auth/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPortalAuditsIdRoute = AppPortalAuditsIdRouteImport.update({
  id: '/audits/$id',
  path: '/audits/$id',
  getParentRoute: () => AppPortalRoute,
} as any)
const AppDashboardClientsIdRoute = AppDashboardClientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppDashboardClientsRoute,
} as any)
const AppDashboardAuditsIdRoute = AppDashboardAuditsIdRouteImport.update({
  id: '/audits/$id',
  path: '/audits/$id',
  getParentRoute: () => AppDashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/account-closed': typeof AccountClosedRoute
  '/complete-setup': typeof CompleteSetupRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/dashboard': typeof AppDashboardRouteWithChildren
  '/portal': typeof AppPortalRouteWithChildren
  '/api/memory': typeof ApiMemoryRoute
  '/admin/agencies': typeof AppAdminAgenciesRoute
  '/admin/clients': typeof AppAdminClientsRoute
  '/admin/logs': typeof AppAdminLogsRoute
  '/admin/settings': typeof AppAdminSettingsRoute
  '/admin/usage': typeof AppAdminUsageRoute
  '/dashboard/audit': typeof AppDashboardAuditRoute
  '/dashboard/clients': typeof AppDashboardClientsRouteWithChildren
  '/dashboard/integrations': typeof AppDashboardIntegrationsRoute
  '/dashboard/market-share': typeof AppDashboardMarketShareRoute
  '/dashboard/settings': typeof AppDashboardSettingsRoute
  '/dashboard/suspended': typeof AppDashboardSuspendedRoute
  '/portal/account': typeof AppPortalAccountRoute
  '/portal/archived': typeof AppPortalArchivedRoute
  '/portal/audit': typeof AppPortalAuditRoute
  '/portal/connect': typeof AppPortalConnectRoute
  '/portal/history': typeof AppPortalHistoryRoute
  '/portal/integrations': typeof AppPortalIntegrationsRoute
  '/admin/': typeof AppAdminIndexRoute
  '/dashboard/': typeof AppDashboardIndexRoute
  '/portal/': typeof AppPortalIndexRoute
  '/dashboard/audits/$id': typeof AppDashboardAuditsIdRoute
  '/dashboard/clients/$id': typeof AppDashboardClientsIdRoute
  '/portal/audits/$id': typeof AppPortalAuditsIdRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
  '/api/auth/google/start': typeof ApiAuthGoogleStartRoute
  '/api/auth/semrush/callback': typeof ApiAuthSemrushCallbackRoute
  '/api/auth/semrush/start': typeof ApiAuthSemrushStartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/account-closed': typeof AccountClosedRoute
  '/complete-setup': typeof CompleteSetupRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/api/memory': typeof ApiMemoryRoute
  '/admin/agencies': typeof AppAdminAgenciesRoute
  '/admin/clients': typeof AppAdminClientsRoute
  '/admin/logs': typeof AppAdminLogsRoute
  '/admin/settings': typeof AppAdminSettingsRoute
  '/admin/usage': typeof AppAdminUsageRoute
  '/dashboard/audit': typeof AppDashboardAuditRoute
  '/dashboard/clients': typeof AppDashboardClientsRouteWithChildren
  '/dashboard/integrations': typeof AppDashboardIntegrationsRoute
  '/dashboard/market-share': typeof AppDashboardMarketShareRoute
  '/dashboard/settings': typeof AppDashboardSettingsRoute
  '/dashboard/suspended': typeof AppDashboardSuspendedRoute
  '/portal/account': typeof AppPortalAccountRoute
  '/portal/archived': typeof AppPortalArchivedRoute
  '/portal/audit': typeof AppPortalAuditRoute
  '/portal/connect': typeof AppPortalConnectRoute
  '/portal/history': typeof AppPortalHistoryRoute
  '/portal/integrations': typeof AppPortalIntegrationsRoute
  '/admin': typeof AppAdminIndexRoute
  '/dashboard': typeof AppDashboardIndexRoute
  '/portal': typeof AppPortalIndexRoute
  '/dashboard/audits/$id': typeof AppDashboardAuditsIdRoute
  '/dashboard/clients/$id': typeof AppDashboardClientsIdRoute
  '/portal/audits/$id': typeof AppPortalAuditsIdRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
  '/api/auth/google/start': typeof ApiAuthGoogleStartRoute
  '/api/auth/semrush/callback': typeof ApiAuthSemrushCallbackRoute
  '/api/auth/semrush/start': typeof ApiAuthSemrushStartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/accept-invite': typeof AcceptInviteRoute
  '/account-closed': typeof AccountClosedRoute
  '/complete-setup': typeof CompleteSetupRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/_app/admin': typeof AppAdminRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRouteWithChildren
  '/_app/portal': typeof AppPortalRouteWithChildren
  '/api/memory': typeof ApiMemoryRoute
  '/_app/admin/agencies': typeof AppAdminAgenciesRoute
  '/_app/admin/clients': typeof AppAdminClientsRoute
  '/_app/admin/logs': typeof AppAdminLogsRoute
  '/_app/admin/settings': typeof AppAdminSettingsRoute
  '/_app/admin/usage': typeof AppAdminUsageRoute
  '/_app/dashboard/audit': typeof AppDashboardAuditRoute
  '/_app/dashboard/clients': typeof AppDashboardClientsRouteWithChildren
  '/_app/dashboard/integrations': typeof AppDashboardIntegrationsRoute
  '/_app/dashboard/market-share': typeof AppDashboardMarketShareRoute
  '/_app/dashboard/settings': typeof AppDashboardSettingsRoute
  '/_app/dashboard/suspended': typeof AppDashboardSuspendedRoute
  '/_app/portal/account': typeof AppPortalAccountRoute
  '/_app/portal/archived': typeof AppPortalArchivedRoute
  '/_app/portal/audit': typeof AppPortalAuditRoute
  '/_app/portal/connect': typeof AppPortalConnectRoute
  '/_app/portal/history': typeof AppPortalHistoryRoute
  '/_app/portal/integrations': typeof AppPortalIntegrationsRoute
  '/_app/admin/': typeof AppAdminIndexRoute
  '/_app/dashboard/': typeof AppDashboardIndexRoute
  '/_app/portal/': typeof AppPortalIndexRoute
  '/_app/dashboard/audits/$id': typeof AppDashboardAuditsIdRoute
  '/_app/dashboard/clients/$id': typeof AppDashboardClientsIdRoute
  '/_app/portal/audits/$id': typeof AppPortalAuditsIdRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
  '/api/auth/google/start': typeof ApiAuthGoogleStartRoute
  '/api/auth/semrush/callback': typeof ApiAuthSemrushCallbackRoute
  '/api/auth/semrush/start': typeof ApiAuthSemrushStartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/account-closed'
    | '/complete-setup'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/terms'
    | '/admin'
    | '/dashboard'
    | '/portal'
    | '/api/memory'
    | '/admin/agencies'
    | '/admin/clients'
    | '/admin/logs'
    | '/admin/settings'
    | '/admin/usage'
    | '/dashboard/audit'
    | '/dashboard/clients'
    | '/dashboard/integrations'
    | '/dashboard/market-share'
    | '/dashboard/settings'
    | '/dashboard/suspended'
    | '/portal/account'
    | '/portal/archived'
    | '/portal/audit'
    | '/portal/connect'
    | '/portal/history'
    | '/portal/integrations'
    | '/admin/'
    | '/dashboard/'
    | '/portal/'
    | '/dashboard/audits/$id'
    | '/dashboard/clients/$id'
    | '/portal/audits/$id'
    | '/api/auth/google/callback'
    | '/api/auth/google/start'
    | '/api/auth/semrush/callback'
    | '/api/auth/semrush/start'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invite'
    | '/account-closed'
    | '/complete-setup'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/terms'
    | '/api/memory'
    | '/admin/agencies'
    | '/admin/clients'
    | '/admin/logs'
    | '/admin/settings'
    | '/admin/usage'
    | '/dashboard/audit'
    | '/dashboard/clients'
    | '/dashboard/integrations'
    | '/dashboard/market-share'
    | '/dashboard/settings'
    | '/dashboard/suspended'
    | '/portal/account'
    | '/portal/archived'
    | '/portal/audit'
    | '/portal/connect'
    | '/portal/history'
    | '/portal/integrations'
    | '/admin'
    | '/dashboard'
    | '/portal'
    | '/dashboard/audits/$id'
    | '/dashboard/clients/$id'
    | '/portal/audits/$id'
    | '/api/auth/google/callback'
    | '/api/auth/google/start'
    | '/api/auth/semrush/callback'
    | '/api/auth/semrush/start'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/accept-invite'
    | '/account-closed'
    | '/complete-setup'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/terms'
    | '/_app/admin'
    | '/_app/dashboard'
    | '/_app/portal'
    | '/api/memory'
    | '/_app/admin/agencies'
    | '/_app/admin/clients'
    | '/_app/admin/logs'
    | '/_app/admin/settings'
    | '/_app/admin/usage'
    | '/_app/dashboard/audit'
    | '/_app/dashboard/clients'
    | '/_app/dashboard/integrations'
    | '/_app/dashboard/market-share'
    | '/_app/dashboard/settings'
    | '/_app/dashboard/suspended'
    | '/_app/portal/account'
    | '/_app/portal/archived'
    | '/_app/portal/audit'
    | '/_app/portal/connect'
    | '/_app/portal/history'
    | '/_app/portal/integrations'
    | '/_app/admin/'
    | '/_app/dashboard/'
    | '/_app/portal/'
    | '/_app/dashboard/audits/$id'
    | '/_app/dashboard/clients/$id'
    | '/_app/portal/audits/$id'
    | '/api/auth/google/callback'
    | '/api/auth/google/start'
    | '/api/auth/semrush/callback'
    | '/api/auth/semrush/start'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AcceptInviteRoute: typeof AcceptInviteRoute
  AccountClosedRoute: typeof AccountClosedRoute
  CompleteSetupRoute: typeof CompleteSetupRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  ApiMemoryRoute: typeof ApiMemoryRoute
  ApiAuthGoogleCallbackRoute: typeof ApiAuthGoogleCallbackRoute
  ApiAuthGoogleStartRoute: typeof ApiAuthGoogleStartRoute
  ApiAuthSemrushCallbackRoute: typeof ApiAuthSemrushCallbackRoute
  ApiAuthSemrushStartRoute: typeof ApiAuthSemrushStartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complete-setup': {
      id: '/complete-setup'
      path: '/complete-setup'
      fullPath: '/complete-setup'
      preLoaderRoute: typeof CompleteSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account-closed': {
      id: '/account-closed'
      path: '/account-closed'
      fullPath: '/account-closed'
      preLoaderRoute: typeof AccountClosedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/memory': {
      id: '/api/memory'
      path: '/api/memory'
      fullPath: '/api/memory'
      preLoaderRoute: typeof ApiMemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/portal': {
      id: '/_app/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AppPortalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/portal/': {
      id: '/_app/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof AppPortalIndexRouteImport
      parentRoute: typeof AppPortalRoute
    }
    '/_app/dashboard/': {
      id: '/_app/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/portal/integrations': {
      id: '/_app/portal/integrations'
      path: '/integrations'
      fullPath: '/portal/integrations'
      preLoaderRoute: typeof AppPortalIntegrationsRouteImport
      parentRoute: typeof AppPortalRoute
    }
    '/_app/portal/history': {
      id: '/_app/portal/history'
      path: '/history'
      fullPath: '/portal/history'
      preLoaderRoute: typeof AppPortalHistoryRouteImport
      parentRoute: typeof AppPortalRoute
    }
    '/_app/portal/connect': {
      id: '/_app/portal/connect'
      path: '/connect'
      fullPath: '/portal/connect'
      preLoaderRoute: typeof AppPortalConnectRouteImport
      parentRoute: typeof AppPortalRoute
    }
    '/_app/portal/audit': {
      id: '/_app/portal/audit'
      path: '/audit'
      fullPath: '/portal/audit'
      preLoaderRoute: typeof AppPortalAuditRouteImport
      parentRoute: typeof AppPortalRoute
    }
    '/_app/portal/archived': {
      id: '/_app/portal/archived'
      path: '/archived'
      fullPath: '/portal/archived'
      preLoaderRoute: typeof AppPortalArchivedRouteImport
      parentRoute: typeof AppPortalRoute
    }
    '/_app/portal/account': {
      id: '/_app/portal/account'
      path: '/account'
      fullPath: '/portal/account'
      preLoaderRoute: typeof AppPortalAccountRouteImport
      parentRoute: typeof AppPortalRoute
    }
    '/_app/dashboard/suspended': {
      id: '/_app/dashboard/suspended'
      path: '/suspended'
      fullPath: '/dashboard/suspended'
      preLoaderRoute: typeof AppDashboardSuspendedRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/_app/dashboard/settings': {
      id: '/_app/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AppDashboardSettingsRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/_app/dashboard/market-share': {
      id: '/_app/dashboard/market-share'
      path: '/market-share'
      fullPath: '/dashboard/market-share'
      preLoaderRoute: typeof AppDashboardMarketShareRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/_app/dashboard/integrations': {
      id: '/_app/dashboard/integrations'
      path: '/integrations'
      fullPath: '/dashboard/integrations'
      preLoaderRoute: typeof AppDashboardIntegrationsRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/_app/dashboard/clients': {
      id: '/_app/dashboard/clients'
      path: '/clients'
      fullPath: '/dashboard/clients'
      preLoaderRoute: typeof AppDashboardClientsRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/_app/dashboard/audit': {
      id: '/_app/dashboard/audit'
      path: '/audit'
      fullPath: '/dashboard/audit'
      preLoaderRoute: typeof AppDashboardAuditRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/_app/admin/usage': {
      id: '/_app/admin/usage'
      path: '/usage'
      fullPath: '/admin/usage'
      preLoaderRoute: typeof AppAdminUsageRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/settings': {
      id: '/_app/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AppAdminSettingsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/logs': {
      id: '/_app/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AppAdminLogsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/clients': {
      id: '/_app/admin/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AppAdminClientsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/agencies': {
      id: '/_app/admin/agencies'
      path: '/agencies'
      fullPath: '/admin/agencies'
      preLoaderRoute: typeof AppAdminAgenciesRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/api/auth/semrush/start': {
      id: '/api/auth/semrush/start'
      path: '/api/auth/semrush/start'
      fullPath: '/api/auth/semrush/start'
      preLoaderRoute: typeof ApiAuthSemrushStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/semrush/callback': {
      id: '/api/auth/semrush/callback'
      path: '/api/auth/semrush/callback'
      fullPath: '/api/auth/semrush/callback'
      preLoaderRoute: typeof ApiAuthSemrushCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/google/start': {
      id: '/api/auth/google/start'
      path: '/api/auth/google/start'
      fullPath: '/api/auth/google/start'
      preLoaderRoute: typeof ApiAuthGoogleStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/google/callback': {
      id: '/api/auth/google/callback'
      path: '/api/auth/google/callback'
      fullPath: '/api/auth/google/callback'
      preLoaderRoute: typeof ApiAuthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/portal/audits/$id': {
      id: '/_app/portal/audits/$id'
      path: '/audits/$id'
      fullPath: '/portal/audits/$id'
      preLoaderRoute: typeof AppPortalAuditsIdRouteImport
      parentRoute: typeof AppPortalRoute
    }
    '/_app/dashboard/clients/$id': {
      id: '/_app/dashboard/clients/$id'
      path: '/$id'
      fullPath: '/dashboard/clients/$id'
      preLoaderRoute: typeof AppDashboardClientsIdRouteImport
      parentRoute: typeof AppDashboardClientsRoute
    }
    '/_app/dashboard/audits/$id': {
      id: '/_app/dashboard/audits/$id'
      path: '/audits/$id'
      fullPath: '/dashboard/audits/$id'
      preLoaderRoute: typeof AppDashboardAuditsIdRouteImport
      parentRoute: typeof AppDashboardRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminAgenciesRoute: typeof AppAdminAgenciesRoute
  AppAdminClientsRoute: typeof AppAdminClientsRoute
  AppAdminLogsRoute: typeof AppAdminLogsRoute
  AppAdminSettingsRoute: typeof AppAdminSettingsRoute
  AppAdminUsageRoute: typeof AppAdminUsageRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminAgenciesRoute: AppAdminAgenciesRoute,
  AppAdminClientsRoute: AppAdminClientsRoute,
  AppAdminLogsRoute: AppAdminLogsRoute,
  AppAdminSettingsRoute: AppAdminSettingsRoute,
  AppAdminUsageRoute: AppAdminUsageRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppDashboardClientsRouteChildren {
  AppDashboardClientsIdRoute: typeof AppDashboardClientsIdRoute
}

const AppDashboardClientsRouteChildren: AppDashboardClientsRouteChildren = {
  AppDashboardClientsIdRoute: AppDashboardClientsIdRoute,
}

const AppDashboardClientsRouteWithChildren =
  AppDashboardClientsRoute._addFileChildren(AppDashboardClientsRouteChildren)

interface AppDashboardRouteChildren {
  AppDashboardAuditRoute: typeof AppDashboardAuditRoute
  AppDashboardClientsRoute: typeof AppDashboardClientsRouteWithChildren
  AppDashboardIntegrationsRoute: typeof AppDashboardIntegrationsRoute
  AppDashboardMarketShareRoute: typeof AppDashboardMarketShareRoute
  AppDashboardSettingsRoute: typeof AppDashboardSettingsRoute
  AppDashboardSuspendedRoute: typeof AppDashboardSuspendedRoute
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
  AppDashboardAuditsIdRoute: typeof AppDashboardAuditsIdRoute
}

const AppDashboardRouteChildren: AppDashboardRouteChildren = {
  AppDashboardAuditRoute: AppDashboardAuditRoute,
  AppDashboardClientsRoute: AppDashboardClientsRouteWithChildren,
  AppDashboardIntegrationsRoute: AppDashboardIntegrationsRoute,
  AppDashboardMarketShareRoute: AppDashboardMarketShareRoute,
  AppDashboardSettingsRoute: AppDashboardSettingsRoute,
  AppDashboardSuspendedRoute: AppDashboardSuspendedRoute,
  AppDashboardIndexRoute: AppDashboardIndexRoute,
  AppDashboardAuditsIdRoute: AppDashboardAuditsIdRoute,
}

const AppDashboardRouteWithChildren = AppDashboardRoute._addFileChildren(
  AppDashboardRouteChildren,
)

interface AppPortalRouteChildren {
  AppPortalAccountRoute: typeof AppPortalAccountRoute
  AppPortalArchivedRoute: typeof AppPortalArchivedRoute
  AppPortalAuditRoute: typeof AppPortalAuditRoute
  AppPortalConnectRoute: typeof AppPortalConnectRoute
  AppPortalHistoryRoute: typeof AppPortalHistoryRoute
  AppPortalIntegrationsRoute: typeof AppPortalIntegrationsRoute
  AppPortalIndexRoute: typeof AppPortalIndexRoute
  AppPortalAuditsIdRoute: typeof AppPortalAuditsIdRoute
}

const AppPortalRouteChildren: AppPortalRouteChildren = {
  AppPortalAccountRoute: AppPortalAccountRoute,
  AppPortalArchivedRoute: AppPortalArchivedRoute,
  AppPortalAuditRoute: AppPortalAuditRoute,
  AppPortalConnectRoute: AppPortalConnectRoute,
  AppPortalHistoryRoute: AppPortalHistoryRoute,
  AppPortalIntegrationsRoute: AppPortalIntegrationsRoute,
  AppPortalIndexRoute: AppPortalIndexRoute,
  AppPortalAuditsIdRoute: AppPortalAuditsIdRoute,
}

const AppPortalRouteWithChildren = AppPortalRoute._addFileChildren(
  AppPortalRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRouteWithChildren
  AppPortalRoute: typeof AppPortalRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppDashboardRoute: AppDashboardRouteWithChildren,
  AppPortalRoute: AppPortalRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AcceptInviteRoute: AcceptInviteRoute,
  AccountClosedRoute: AccountClosedRoute,
  CompleteSetupRoute: CompleteSetupRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  ApiMemoryRoute: ApiMemoryRoute,
  ApiAuthGoogleCallbackRoute: ApiAuthGoogleCallbackRoute,
  ApiAuthGoogleStartRoute: ApiAuthGoogleStartRoute,
  ApiAuthSemrushCallbackRoute: ApiAuthSemrushCallbackRoute,
  ApiAuthSemrushStartRoute: ApiAuthSemrushStartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
